cricket/urls.py
from django.urls import path, re_path

from cricket.views import *

urlpatterns = [
    path('', index, name='home'),
    path('teams/', teams, name='teams'),
    path('team/<slug>/', teams, name='team'),
    path('players/', players, name='players'),
    path('player/<slug>/', players, name='player'),
]

ustech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cricket.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cricket/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.timezone import now
from django.db.models import Sum, F, Max, Q

# Create your models here.

COUNTRIES = (
        (1, 'India'),
        (2, 'South Africa'),
        (3, 'Pakistan'),
        (4, 'Nepal'),
    )


class Team(models.Model):
    name = models.CharField(max_length=255)
    club = models.CharField(max_length=255, blank=True, null=True)
    slug = models.SlugField(max_length=255, unique=True)
    logo = models.ImageField(upload_to='team.logo', max_length=255, blank=True, null=True)

    objects = models.Manager()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Team, self).save(*args, **kwargs)

    def get_match_played(self):
        ''' Gets match played by team '''
        return Match.objects.filter(Q(home_team=self) | Q(away_team=self)).count()

    def get_match_wins_count(self):
        ''' Gets match wins by team '''
        return Match.objects.filter(winner_team=self).count()

    def get_match_loss_count(self):
        ''' Gets match loss by team '''
        return self.get_match_played() - self.get_match_wins_count()


class Player(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    avatar = models.ImageField(upload_to='player.avatar', max_length=255, blank=True, null=True)
    jersey_number = models.IntegerField(default=0)
    team = models.ForeignKey(Team, related_name='players', on_delete=models.CASCADE)
    country = models.IntegerField(choices=COUNTRIES, default=1)

    objects = models.Manager()

    def __str__(self):
        return self.slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.first_name + '-' + self.last_name)
        super(Player, self).save(*args, **kwargs)

    def full_name(self):
        ''' Gets full name of player '''
        return self.first_name + ' ' + self.last_name

    def get_match_played(self):
        ''' Gets match played count by player '''
        return Performance.objects.filter(player=self).count()

    def get_runs_count(self):
        ''' Gets total runs by player '''
        return Performance.objects.filter(player=self).aggregate(Sum('runs'))['runs__sum']

    def get_50s_count(self):
        ''' Gets number of times 50 to 99 runs scored by player'''
        return Performance.objects.filter(player=self, runs__range=[50, 99]).count()

    def get_100s_count(self):
        ''' Gets number of times 100+ runs scored by player'''
        return Performance.objects.filter(player=self, runs__gte=100).count()

    def get_highest_score(self):
        ''' Gets players highest score '''
        return Performance.objects.filter(player=self).aggregate(Max('runs'))['runs__max']


class Match(models.Model):
    home_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='home_team')
    away_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='away_team')
    winner_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='winner_team')
    match_date = models.DateField(blank=True, default=now, help_text='The date when this match will be play.')

    class Meta:
        verbose_name_plural = "Matches"

    def __str__(self):
        return self.home_team.name + ' v/s ' + self.away_team.name

    objects = models.Manager()


class Performance(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    runs = models.IntegerField(default=0)
    balls_faced = models.IntegerField(default=0)

    objects = models.Manager()

    class Meta:
        unique_together = ('match', 'player')

cricket/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import Http404
# Create your views here.
from cricket.models import Team, Player, Match


def index(request):
    """
    :param request:
    :return:

    this function will returns home page data in context
    """

    context = {}
    context['teams_count'] = Team.objects.count()
    context['players_count'] = Player.objects.count()
    context['match_count'] = Match.objects.count()

    return render(request, 'index.html', context=context)


def teams(request, slug=None):
    """

    :param request:
    :param slug:
    :return:

    This views return all teams and team's players data on base of team_slug argument.
    """

    context = {}

    if slug:
        try:
            context['team'] = Team.objects.prefetch_related('players').get(slug=slug)

        except Team.DoesNotExist:
            raise Http404

        return render(request, 'team.html', context=context)

    else:
        context['teams'] = Team.objects.prefetch_related('players').all()

        return render(request, 'team.html', context)


def players(request, slug=None):
    """

    :param request:
    :param slug:
    :return:

    This view return all players and single player data on base of player_slug.
    """
    context = {}
    if not slug:
        context['players'] = Player.objects.select_related('team').all()

    else:
        try:
            context['player'] = Player.objects.select_related('team').get(slug=slug)

        except Team.DoesNotExist:
            raise Http404

    return render(request, 'player.html', context)

cricket/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table>
    <thead>
        <td>Name</td>
        <td>Counts</td>
    </thead>
    <tr>
        <td><a href="{% url 'teams' %}">Teams</a></td>
        <td>{{ teams_count }}</td>
    </tr>
     <tr>
        <td><a href="{% url 'players' %}">Players</a></td>
        <td>{{ players_count }}</td>
    </tr>
    <tr>
        <td>Matches</td>
        <td>{{ match_count }}</td>
    </tr>
</table>
</body>
</html>

cricket/templates/player.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{%if players %}

<h2> All Teams Player List : </h2>
<table>
    {% for player in players %}
    <tr>
        <td>{{ forloop.counter }}.</td>
        <td><a href="{% url 'player' player.slug %}" >{{ player.first_name }}</a></td>
        <td><a href="{% url 'player' player.slug %}" >{{ player.last_name }}</a></td>
        <td> <a href="{% url 'team'  player.team.slug %}"> {{ player.team.name }} </a>  </td>
        <td><img src="{{ player.avatar.url }}" style="max-height:300px"> </td>
    </tr>
    {% endfor %}
</table>
{%endif%}


{%if player %}
<h2>{{player.full_name}}  details: </h2>
<ul>
    <li>First Name: {{ player.first_name }}</li>
    <li>Last Name: {{ player.last_name }}</li>
    <li>Team: <a href="{% url 'team' player.team.slug %}">{{ player.team.name }}</a> </li>
    <li>Country Name: {{ player.get_country_display }}</li>
    <li>Jersey Number: {{ player.jersey_number }}</li>
    <li>Total Match Played: {{ player.get_match_played }}</li>
    <li>Total runs: {{ player.get_runs_count }}</li>
    <li>Highest Score: {{ player.get_highest_score }}</li>
    <li>Fifties Count: {{ player.get_50s_count }}</li>
    <li>Hundreds Count: {{ player.get_100s_count }}</li>
    <li>Logo: <img src="{{ player.avatar.url }}" style="max-height:200px;"> </li>
    </li>

</ul>
{%endif%}

</body>
</html>

cricket/templates/team.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>



{%if teams %}
<h2> All Teams : </h2>
<table>
    <thead>
    <td>Sno</td>
    <td>Team Name</td>
    <td>Logo</td>

    <td>Match <br> Played</td>
    <td>Match <br> Winner</td>
    <td>Match <br> Lost</td>
    </thead>
    {% for team in teams %}
    <tr>
        <td>{{ forloop.counter }}.</td>
        <td><a href="{% url 'team' team.slug %}" >{{ team.name }}</a></td>
        <td><a href="{% url 'team' team.slug %}" ><img src="{{ team.logo.url }}" style="max-height:50px"></a></td>

         <td>{{ team.get_match_played }}</td>
         <td>{{ team.get_match_wins_count }}</td>
         <td>{{ team.get_match_loss_count }}</td>
    </tr>
    {% endfor %}
</table>
{%endif%}


{%if team %}
<h2>Players List of Team:  {{ team.name }}</h2>
<table>

    <thead>
    <td>Team Name</td>
    <td>Logo</td>
    <td>Players</td>
    </thead>
    <tr>
        <td>{{ team.name }}</td>
        <td><img src="{{ team.logo.url }}" style="max-height:300px"></td>
        <td>
              <ul>
                {% for player in team.players.all %}
                <li>{{ forloop.counter }} .<a href="{% url 'player' player.slug %}"> {{ player.full_name }}</a></li>
                {% endfor %}
            </ul>
        </td>
    </tr>

</table>
{%endif%}

</body>
</html>